New error logging
devexperts/gwtscript pull request #1
Opened 2022-01-19 10:54 UTC by Astroner

2022-01-24 07:49 UTC, ipavelleds requested changes

2022-01-24 07:49 UTC, ipavelleds commented on src/parser/getNodesToTranspile.ts
> +                    console.warn(
Could we show these warnings at the end of logs? 'cause we could easily miss these warnings

2022-01-24 07:49 UTC, ipavelleds commented on src/utils/joinLeft.ts
> +    return leftEither;
could be simplified
```typescript
pipe(
        either,
        mapLeft(getOrElseW(identity))
    )
```

2022-01-24 07:49 UTC, ipavelleds commented on src/utils/sequenceReaderEither.ts
> +    return right(values);
can be simplified
```typescript
pipe(
    items,
    partitionMap(r => r(env)),
    ({ left, right}) => (
        pipe(
            right,
            eitherFromPredicate(constant(array.isEmpty(left)), constant(left))
        )
    )
)
```

2022-01-25 09:34 UTC, Astroner commented on src/parser/getNodesToTranspile.ts
> +                    console.warn(
I think no, we can't coz for this improvement I'll have to refactor whole the code(replace Either with These)

2022-01-25 10:43 UTC, ipavelleds approved these changes

2022-01-26 08:05 UTC, merged